name: Test the frontend with npm and all dependencies
description: ""

runs:
  using: composite
  steps:
    - name: Use node js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Cache node modules
      uses: actions/cache@v3
      id: cache-npm
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      shell: bash
      # if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      run: npm ci

    - name: Test the app
      shell: bash
      run: npm run test

    - name: Build the app
      shell: bash
      run: npm run build

    # need to continue deploying the changes, hence, disabling the performance audits for mobile since there're some perf issues to be fixed
    # - name: Run lighthouse mobile audit
    #   shell: bash
    #   run: npm run lhci:mobile

    - name: Run lighthouse desktop audit
      shell: bash
      run: npm run lhci:desktop
