name: Test the frontend with npm and all dependencies
description: ""

runs:
  using: composite
  steps:
    - name: Use node js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Cache node modules
      uses: actions/cache@v3
      id: cache-npm
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      shell: bash
      # if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      run: npm ci

    - name: Test the app
      shell: bash
      run: npm run test

    - name: Run the app
      shell: bash
      run: npm run dev & npx wait-on http://localhost:5173

    - name: Test accessibility of the app using axe CLI
      shell: bash
      run: |
        npm install -g @axe-core/cli
        axe http://localhost:5173 --exit
