name: Build & deploy frontend to production

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v4

      - name: Run the frontend tests and build the app
        uses: ./.github/actions/test-frontend

      - run: npm run build --if-present

      - name: Run the app
        shell: bash
        run: npm run dev & npx wait-on --timeout 60000 http://[::1]:5173

      - name: Test accessibility of the app using axe CLI
        shell: bash
        run: |
          npm install -g @axe-core/cli
          axe http://localhost:5173 --exit

  deploy-frontend:
    needs: test-frontend
    uses: sjsouvik/Github-actions-demo/.github/workflows/deploy-frontend.yml@main
    secrets: inherit # Secrets are not automatically passed to reusable workflows. Workflows that call reusable workflows in the same organization or enterprise can use the `inherit` keyword to implicitly pass the secrets to the called workflow. Reference: https://github.blog/changelog/2022-05-03-github-actions-simplify-using-secrets-with-reusable-workflows/, https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
