name: "test frontend"

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3

      - name: Run the frontend tests
        uses: ./.github/actions/test-frontend

  build-app:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Build the app
        shell: bash
        run: npm run build
